# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

name: ASP.NET Core 8 API Deployment to IIS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.x 

      - name: Restore NuGet packages
        run: dotnet restore

      - name: Build
        run: dotnet build

      - name: Publish
        run: dotnet publish -c Release -o ./publish

      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: aspnetcore-api
          path: ./publish

